### ISSUE TITLE
Problemas instalando

### ISSUE THREAD

**Issue by badgercl** [datal-org/datal#21]
Hola,

Seguí las instrucciones en https://github.com/datal-org/datal/blob/master/README.md 
En el punto 5. Iniciar el servicio Web al ejecutar ``sudo supervisorctl start uwsgi`` dentro de la máquina virtual me sale el mensaje:

     vagrant@vagrant-ubuntu-trusty-64:~$ sudo supervisorctl start uwsgi
     uwsgi: ERROR (no such process)

¿Falta algún paso?

Gracias!

**Comment by ignacionf** [comment]
podes ejecutar:
vagrant ssh
sudo salt-call state.highstate 

Luego nos copias el resultado?

Gracias.

**Comment by pupii** [comment]
A me paso lo mismo, y aparentemente fue porque no tenia las versiones correctas de VirtualBox y de Vagrant. Fijate de respetar VirtualBox 4.x y Vagrant 1.7.2

Espero se de ayuda.

**Comment by badgercl** [comment]
Me sale este error:

    ----------
          ID: reindex
    Function: cmd.run
        Name: PATH="/home/vagrant/env/bin/:$PATH"; python manage.py index --settings=workspace.settings --re-index
      Result: False
     Comment: Command "PATH="/home/vagrant/env/bin/:$PATH"; python manage.py index --settings=workspace.settings --re-index" run
     Started: 17:29:52.856789
    Duration: 1713.318 ms
     Changes:
              ----------
              pid:
                  20849
              retcode:
                  1
              stderr:
                  Traceback (most recent call last):
                    File "manage.py", line 19, in <module>
                      execute_from_command_line(sys.argv)
                    File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
                      utility.execute()
                    File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
                      self.fetch_command(subcommand).run_from_argv(self.argv)
                    File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
                      klass = load_command_class(app_name, subcommand)
                    File "/home/vagrant/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 75, in load_command_class
                      module = import_module('%s.management.commands.%s' % (app_name, name))
                    File "/home/vagrant/env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
                      __import__(name)
                    File "/home/vagrant/app/core/management/commands/index.py", line 8, in <module>
                      from core.lifecycle.datasets import DatasetLifeCycleManager
                    File "/home/vagrant/app/core/lifecycle/datasets.py", line 9, in <module>
                      from core.lifecycle.datastreams import DatastreamLifeCycleManager
                    File "/home/vagrant/app/core/lifecycle/datastreams.py", line 9, in <module>
                      from core.daos.datastreams import DataStreamDBDAO, DatastreamSearchDAOFactory
                    File "/home/vagrant/app/core/daos/datastreams.py", line 6, in <module>
                      from core.lib.searchify import SearchifyIndex
                    File "/home/vagrant/app/core/lib/searchify.py", line 3, in <module>
                      from indextank.client import ApiClient
                  ImportError: No module named indextank.client
              stdout:
                  PASO1-9
----------
    

El Vagrant lo bajé hoy y Virtualbox es 4.3.18

**Comment by danielpadula** [comment]
Por favor proba en la rama develop. Hoy pasamos a master una versión nueva con los últimos fixes. Mientras tanto por favor probar en develop

**Comment by badgercl** [comment]
si , estaba mirando master, por estar navegando en las secciones termine en el home y no me percaté que el link que habían enviado apuntaba a develop :)

Funciona perfecto ahora. ¡Muchas gracias!
